dev/Paper-Mining/config/routes.rb
PaperMining::Application.routes.draw do
  resources :papers

end

dev/Paper-Mining/app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :abstract, :author, :content, :id, :local_path, :title, :url
end

dev/Paper-Mining/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

dev/Paper-Mining/app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end
end

dev/Paper-Mining/app/helpers/application_helper.rb
module ApplicationHelper
end

dev/Paper-Mining/app/helpers/papers_helper.rb
module PapersHelper
end

dev/Paper-Mining/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperMining</title>
  
</head>
<body>

<%= yield %>

</body>
</html>

dev/Paper-Mining/app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :local_path %><br />
    <%= f.text_field :local_path %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dev/Paper-Mining/app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

dev/Paper-Mining/app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Url</th>
    <th>Local path</th>
    <th>Abstract</th>
    <th>Content</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.id %></td>
    <td><%= paper.title %></td>
    <td><%= paper.url %></td>
    <td><%= paper.local_path %></td>
    <td><%= paper.abstract %></td>
    <td><%= paper.content %></td>
    <td><%= paper.author %></td>
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %>

dev/Paper-Mining/app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

dev/Paper-Mining/app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @paper.id %>
</p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Url:</b>
  <%= @paper.url %>
</p>

<p>
  <b>Local path:</b>
  <%= @paper.local_path %>
</p>

<p>
  <b>Abstract:</b>
  <%= @paper.abstract %>
</p>

<p>
  <b>Content:</b>
  <%= @paper.content %>
</p>

<p>
  <b>Author:</b>
  <%= @paper.author %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>